### ISSUE TITLE
FPS drop (TBC)

### ISSUE THREAD

**Issue by GioBego** [shagu/pfQuest#112]
patch didn't help to resolve the issue and I observed following:
- it is NOT related to minimap nodes -  I turned minimap nodes off and fps are still low
- interesting is ... when I open the world map, FPS goes back to max .... so it is low only while world map is closed so I asume it is extensively computing something in background
- shift click and hiding the quest with many nodes resolves the problem

**Comment by GioBego** [comment]
so I turned all addons off and tested ... should have been obvious to me ... the collision is with quest helper (I use for quest tracker, that tracks active quests automatically and allows to change font size of tracker)

**Comment by GioBego** [comment]
still getting big lag when Accepting quest with many nodes .... but after that, fps is ok

**Comment by GioBego** [comment]
lag is back with pfQuest questlog enabled .... same lag after acquiring first quest item ... maybe looking to quest database causing the lag

**Comment by shagu** [comment]
I think you should increase the Minimum Item Drop Chance, if your PC can't handle to display all drops:
![image](https://user-images.githubusercontent.com/11586807/95023673-a5120680-067e-11eb-867a-0c87148804fe.png)

**Comment by GioBego** [comment]
have set it to 5 from the beginning ... and fps drop is affecting everybody I play with no matter how powerfull pc they have

btw I was using full version ... testing now en_US version, but didn't have quest with that many nodes since then ... will report if I get any significant change
it seems it is not pc cant hanle it ... fps drop is only when map is closed ... when I open map I have max fps back with all nodes on ... so strange ... hope we will figure it out, I will try and test whatever comes to my mind

**Comment by shagu** [comment]
I also get a single freeze for exactly 0.38 seconds when obtaining the quest "Mending Old Wounds
" (<https://classicdb.ch/?quest=9267>) which is because there are plenty of possible spots to farm "Line Cloth" from. When setting the Minimum Loot Chance to 50%, I no longer get that short freeze, however, it no longer shows any of the useful grind spots. So one simply has to decide if all possible spawns should be shown or not. I'd rather have it accurate and live with the stutter for less than a second on less than 1% of the quests. But it's up to you.

Regarding the FPS loss while the map is closed, I simply cannot reproduce it. It doesn't matter how frustrated you are and how many "..." you write. As long as you won't come up with any useful information such as which addons are in use and which specific quests are causing it, I will not be able to help you. Since I never had such a thing happened on my end, I highly assume it's a combination of addons that makes it happen, but who knows...

Put me in a state where I can reproduce it, and I will gladly spend some hours to fix it (if even possible).

**Comment by shagu** [comment]
The only idea I have, is that one of your addons is calling "SetMapToCurrentZone()" repeatedly which causes pfQuest to update its nodes, since a "WORLD_MAP_UPDATE" event is triggered. With verison 5.2.7, the current zone is now cached and `pfMap.UpdateNodes()` is only alled when the zone changed. That's all I could do for now.

**Comment by GioBego** [comment]
can confirm QuestHelper is causing the problem and it looks like update with caching helped
