### ISSUE TITLE
strange behavior with updating the path to the nearest quest

### ISSUE THREAD

**Issue by Artur91425** [shagu/pfQuest#123]
Very strange behavior and bug. The path to the nearest quest and on the widget (arrow) begins to update and constantly switch between the two quests. After lengthy tests, we found out that this behavior is influenced by the state of BATTLE! When my character is attacked after 2-3 hits, update. It's the same when I attack. Once it turned out to make a situation where the arrow was updated with each hit with an auto attack (every 1-1.5 seconds). Again, the update does not occur between all quests, but only some two...

https://youtu.be/ydsmqoFbtjc

**Comment by Artur91425** [comment]
Loaded only pfQuest (latest version 11/22/2020). In the addon settings, absolutely all the checkboxes are checked.

**Comment by shagu** [comment]
Could you please enable `/db debug` and include the output in your recording?

**Comment by Artur91425** [comment]
https://youtu.be/EixOfSAHIaM

**Comment by shagu** [comment]
Interesting.. :thinking:

**Comment by shagu** [comment]
Ah, seems to be because you gained new skills (Weapon Skill, Defense, ...).
pfQuest updates the Quest Givers when new skills are detected (`SKILL_LINES_CHANGED`), in order to add/update proffession-only quests. So having an update fired is working as expected. However, looks like the sorting mechanism should get some updates here :smirk:

**Comment by shagu** [comment]
Fixed by https://github.com/shagu/pfQuest/commit/5e0f7f48e2947ba6b11bc1d6ae292830ca0da1c3
