### ISSUE TITLE
Wrong Quest Level

### ISSUE THREAD

**Issue by nonameform** [shagu/pfQuest#133]
I know a quest at Darnassus that leads to Darkshore and requires level 14 to pick up. However, pfQuest does not display the marker (or the quest in tooltip for NPC) unless I disable **Display Level +3 Quest Givers**. Then it displays is it as level 100 quest, even though in tooltip it shows it as level 14.

![WoWScrnShot_020921_121434](https://user-images.githubusercontent.com/34381716/107342512-57485780-6ad1-11eb-8d57-6d1395a942c6.jpg)
![WoWScrnShot_020921_121437](https://user-images.githubusercontent.com/34381716/107342540-60392900-6ad1-11eb-9120-6c1946ee3a22.jpg)

**Comment by shagu** [comment]
Thanks for your report. :+1: 

It was basically two bugs:
1st: The behaviour of level +3 questgivers was inverted (Fixed by https://github.com/shagu/pfQuest/commit/80ba9024dcedcd8f5415719f096fcde28557041c https://github.com/shagu/pfQuest/commit/09f80c19440a461eee285f23ac10f83e72408cb2)
2nd: The tracker wrongly assigned a static number to high level quests (Fixed by https://github.com/shagu/pfQuest/commit/706e04bec07eadc90e744bf681c69da5a1bc36cf)

It will be fixed in the version 6.2.3
