### ISSUE TITLE
Stutters with custom quests

### ISSUE THREAD

**Issue by xIGBClutchIx** [shagu/pfQuest#138]
After taking a look into some stutters going on with custom quests and pfQuest on Turtle WoW. I think I found the exact cause of the said issue but not sure what would be the best correction for fixing it.

It looks like the [Levenshtein algorithm loop here](https://github.com/shagu/pfQuest/blob/05d480bf13010eda68c8e84b20e5e8edc7ff5a1d/database.lua#L1410) is causing huge lag spikes especially when multiple custom quests are present. They always seem to hit [line 1426](https://github.com/shagu/pfQuest/blob/05d480bf13010eda68c8e84b20e5e8edc7ff5a1d/database.lua#L1426) in the end.

The solutions I came up with were:

1.  Remove the algorithm and hope the quest text matches up correctly. This would mean the database would need to be perfect I assume. Could cause some issues I assume as that is there, to begin with.
2. Adding a config toggle that toggles off the algorithm so anyone that is on a custom server would suffer the consequences of the removal but would be without said stutters. Seems a bit hacky tbh.
3. A whole new algorithm. Not sure really of anything that would be faster or better.

**Comment by shagu** [comment]
I'm aware of that, and spent hours to reduce the lag to a minimum while I have added it.

> Remove the algorithm and hope the quest text matches up correctly. This would mean the database would need to be perfect I assume. Could cause some issues I assume as that is there, to begin with.

That's not an option and breaks too many quests on too many servers.

> Adding a config toggle that toggles off the algorithm so anyone that is on a custom server would suffer the consequences of the removal but would be without said stutters. Seems a bit hacky tbh.

You'd loose about 20% quests that would actually work with it by doing so.

> A whole new algorithm. Not sure really of anything that would be faster or better.

Good luck! :)

**Comment by xIGBClutchIx** [comment]
Dang yeah thought that would be the case really. Quite unfortunate as the [Turtle Wow community](https://forum.turtle-wow.org/viewtopic.php?f=18&t=2001) quest was having a few issues as there are quite a bit of custom quests.

**Comment by xIGBClutchIx** [comment]
I did just notice something. Custom quests seem to endlessly loop through due to the cache not setting anything on [line 1426](https://github.com/shagu/pfQuest/blob/05d480bf13010eda68c8e84b20e5e8edc7ff5a1d/database.lua#L1426) not sure if this intended also but could set something like title there?

**Comment by shagu** [comment]
> I did just notice something. Custom quests seem to endlessly loop through due to the cache not setting anything on [line 1426](https://github.com/shagu/pfQuest/blob/05d480bf13010eda68c8e84b20e5e8edc7ff5a1d/database.lua#L1426) not sure if this intended also but could set something like title there?

Good catch, using quest ID 0 now for unknown quests <https://github.com/shagu/pfQuest/commit/8128d6ddb994bf2110c4ca1b46eb2a90fe5ebe29>

**Comment by xIGBClutchIx** [comment]
Awesome yeah that should hopefully help a bit. Sadly don't think we can really fix the issue fully so probably best to close this unless you have any ideas.

But I was thinking we could possibly add something where you can load a custom database on top of the normal one so if a server or someone could distribute a file and then users could load it for that server.

**Comment by xIGBClutchIx** [comment]
A unintended side effect commit 8128d6ddb994bf2110c4ca1b46eb2a90fe5ebe29 makes it so custom quests are not able to be tracked in the tracker now. Possibly store a hash of the title?

I fixed with commit: 75744cb4cc9875ade3938b5483601de0eaba7c11 but not sure if we want to return the title.

**Comment by shagu** [comment]
Please review the following changes:
https://github.com/shagu/pfQuest/commit/275877665770be6511e591ab07bd1c35e75649bd https://github.com/shagu/pfQuest/commit/3d190e9da83a228facd236ae8ec93bcf9ea3ef77 https://github.com/shagu/pfQuest/commit/42564a0b42c62b80f9f0f1d85878146f8d56a725 https://github.com/shagu/pfQuest/commit/cb07c92bd1e1369f187581a578210dcf8c821982

- quest title is used for unknown quests instead of ID 0, all calls of the GetQuestIDs functions have been adapted (hopefully)
- the history migration of old versions no longer deletes the string-indexes of custom quests
- the journal displays the title of unknown quests
- the journal can send questlinks with a proper name (using id as title and 0 as id)

**Comment by shagu** [comment]
I also added an option to reset the addon cache (which resets the already identified quests) via https://github.com/shagu/pfQuest/commit/f59eb2c7b8cec23341a2800cc5a0884dad997d5c
You might need to run it, in order to turn the custom-id-0 quests into custom-id-title ones.

It is tagged and released as 6.3.7 now.

**Comment by xIGBClutchIx** [comment]
Works great and looking good here! Seems to have fixed most people stutters that we were seeing too.
