### ISSUE TITLE
Feature Request - WOTLK (3.3.5a)

### ISSUE THREAD

**Issue by xIGBClutchIx** [shagu/pfQuest#156]
It looks like a bit of the code is there for WOTLK. But doesn't look like the toolbox supports it so no database files.

**Comment by rbpaiett** [comment]
Yes, please make an update for LK if possible.  The old Mobmap addon had a feature that would add info to the database as players would come across them.  Then those players could upload them to the devs for updating. Perhaps this is a possibility.

**Comment by AnthonyPaulO** [comment]
This is such an awesome and amazing add-on!! I'm guessing there's some blockers that prevents it from working for WOTLK?

**Comment by shagu** [comment]
I personally don't play WotLK at the moment. Maybe someday when I'll return to WotLK it consider doing it.
The biggest work would be to extend the `toolbox/extractor.lua` to obtain data from TrinityCore/AzerothCore.
Porting the rest of the addon should be rather easy.

**Comment by AnthonyPaulO** [comment]
> I personally don't play WotLK at the moment. Maybe someday when I'll return to WotLK ill consider doing it. The biggest work would be to extend the `toolbox/extractor.lua` to obtain data from TrinityCore/AzerothCore. Porting the rest of the addon should be rather easy.

Thank you for replying! I believe I'm almost done but trying to debug an issue with skillline professions and locales in the extractor. I hope you don't mind but I have a quick question... I see in load-client-data you have certain exceptions in place for the russian language, such as the following:
    if [ "$loc" = "ruRU" ] && [ "$v" == "vanilla" ]; then index=0; fi
Would you be able to tell me what this is for? From the looks of it you seem to be compensating for an issue with the russian locale db having the russian translation in the english column rather than the russian column, and I'm guessing it's because there's no such russian column in vanilla. 

Also, where do you get your DBC data from? I see your vanilla skillline data in client-data-sql has all the tranlsations, but when I look at a DBC dump done in Questie (their DBC-dump-UnpackMe.7z file) which relies on WoWTools, I don't see any translations for SkillLine at all; all the skillline locale files are the same english file. Do you have your data somewhere I can access, or can you tell me how you got them? Many thanks Shagu!

**Comment by shagu** [comment]
First of all sorry for the late reply, i completely forgot answering this.

> Thank you for replying! I believe I'm almost done  [...]

Do you have it public somewhere? And did you made it properly, so that the extractor can now extract all 3 expansions and not just one? Would love to see what you did so far.

> I see in load-client-data you have certain exceptions in place for the russian language, such as the following:
if [ "$loc" = "ruRU" ] && [ "$v" == "vanilla" ]; then index=0; fi
Would you be able to tell me what this is for? From the looks of it you seem to be compensating for an issue with the russian locale db having the russian translation in the english column rather than the russian column, and I'm guessing it's because there's no such russian column in vanilla.

That's right, there exists no ruRU client for 1.12, but there's an unofficial one where all translations where made by replacing the english strings. Therefore when extracting the DBCs, I have to set the language id accordingly.

> Also, where do you get your DBC data from?

I have the clients of all languages on my PC and used the tools from [cmangos](https://github.com/cmangos) to extract the DBC files from them. But there's also a tool called MPQExtractor that can be used for the task. I then used another tool called DBCUtil.exe to convert those DBC files into CSVs. Those CSVs I then convert to SQL via the load-client-data.sh script to be later be able to query it from the extractor.lua.

**Comment by nichlasmm** [comment]
Any news to this, im still hoping for it to happen some day. Best questing addon but sadly only for the earlier versions of the game

**Comment by rockingdice** [comment]
@AnthonyPaulO Could you share your work? I may provide some help.

**Comment by shagu** [comment]
There's a working 3.3.5a version (with only Vanilla and TBC data so far) on the `wotlk` branch:
https://github.com/shagu/pfQuest/tree/wotlk

Once I found time to write the extractors to obtain data from Azeroth Core, I will merge that branch into master.

**Comment by nichlasmm** [comment]
> There's a working 3.3.5a version (with only Vanilla and TBC data so far) on the `wotlk` branch: https://github.com/shagu/pfQuest/tree/wotlk
> 
> Once I found time to write the extractors to obtain data from Azeroth Core, I will merge that branch into master.

You are the best @Shagu much love from here. Keep up the good work!
