### ISSUE TITLE
Quest: The Harvest Golem Mystery (bug?)

### ISSUE THREAD

**Issue by khoopek** [shagu/pfQuest#212]
for the quest, we're supposed to collect 'Intact Animation Rune':
![image](https://github.com/shagu/pfQuest/assets/110908179/44e2d495-d116-4a2c-9d82-ac700cc6c94b)
![image](https://github.com/shagu/pfQuest/assets/110908179/9da29055-ed22-4604-a7e4-ce02980b4f87)

Mouse hover mob 'Harvest Golem' shows wrong item:
![image](https://github.com/shagu/pfQuest/assets/110908179/e37aa910-b31a-4f92-a7fe-d5c76cd19ed1)

Also shows wrong item for mob 'Harvest Watcher' (which should not show for this quest, but previous quest):
![image](https://github.com/shagu/pfQuest/assets/110908179/014e2fb8-9fd2-411d-aeab-0588467fdb66)

**Comment by shagu** [comment]
Do you have the latest version of pfQuest-turtle (the one from yesterday)?

If this issue is still existing after updating to the latest version, please re-open the issue on the
pfQuest-turtle wow bugtracker, as it is an issue with the database there. There are better chances that someone there would pick it up and send a pull-request for it.
