### ISSUE TITLE
browser: add spawn and item id's

### ISSUE THREAD

**Issue by Lichery** [shagu/pfQuest#31]
Please add id in browser. Something like that:
![bandicam 2017-11-17 21-12-54-651](https://user-images.githubusercontent.com/24303693/32962164-804eddc6-cbdc-11e7-989c-037778c1585c.jpg)
This will help you quickly find out the id by name and find on the Internet quickly the information you need.
It would also be very convenient to do a two-way search. By name and by id.

**Comment by Lichery** [comment]
And for quests :)

**Comment by Muehe** [comment]
I have a [semi-complete solution](https://gist.github.com/Muehe/fc69c37f46d2da3580b8b008d05078ce) for this by using the tooltips of the search results. It works for items and quests (adds additional values and formatting for quests too):

![pfquest itemtooltip](https://user-images.githubusercontent.com/8838573/33226455-5f1a737e-d18e-11e7-83c6-e6fbeab4b85e.png)
![pfquest questtooltip](https://user-images.githubusercontent.com/8838573/33226457-6340e406-d18e-11e7-9738-452f2eb0851d.png)

Couldn't show IDs for spawns, because they are not in the DB file, but I added some other stuff:

![pfquest spawntooltip](https://user-images.githubusercontent.com/8838573/33226459-691729da-d18e-11e7-8e28-bee00935110a.png)

**Comment by Lichery** [comment]
the information in the tooltip looks very good, I like it. But I think that also need to add the ID to the browser. It will be more convenient and clearer. And if implement a two-way search, then it will be great :)

**Comment by Muehe** [comment]
How about this (also adds quest level colored according to difficulty):

![screenshot_2017-11-28_20-26-04](https://user-images.githubusercontent.com/8838573/33340657-ffacf4a6-d47c-11e7-9143-7376a59eb80b.png)
![screenshot_2017-11-28_20-40-08](https://user-images.githubusercontent.com/8838573/33340661-03120730-d47d-11e7-91e5-80b39dc78459.png)

```diff
diff --git a/pfBrowser.lua b/pfBrowser.lua
index 3fb247b..0e2bde4 100644
--- a/pfBrowser.lua
+++ b/pfBrowser.lua
@@ -708,7 +708,7 @@ function pfBrowser:SearchItem(search)
               ITEM_QUALITY_COLORS[itemQuality].g * 255,
               ITEM_QUALITY_COLORS[itemQuality].b * 255)
 
-          this.text:SetText(this.itemColor .."|Hitem:"..this.itemID..":0:0:0|h[".. this.itemName.."]|h|r")
+          this.text:SetText(this.itemColor .."|Hitem:"..this.itemID..":0:0:0|h[".. this.itemName.."]|h|r |cff9d9d9d("..this.itemID..")|r")
           this.text:SetWidth(this.text:GetStringWidth())
           this:SetScript("OnUpdate", nil)
         end
@@ -764,7 +764,7 @@ function pfBrowser:SearchQuest(search)
       end
 
       if quests[quest] then
-        button.text:SetText("|cffffcc00|Hquest:0:0:0:0|h[" .. questname .. "]|h|r")
+        button.text:SetText(pfDatabase:HexDifficultyColor(quests[quest]["lvl"]).."["..quests[quest]["lvl"].."]|r |cffffcc00|Hquest:0:0:0:0|h[" .. questname .. "]|h|r |cff9d9d9d("..quests[quest]["id"]..")|r")
       else
         button.text:SetText("|cffff5555[?] |cffffcc00|Hquest:0:0:0:0|h[" .. questname .. "]|h|r")
       end

```

As with the tooltips, the spawns lack the ID to show, and I haven't had time to set up all the stuff required for a full extract, so I can't do anything about that for now.
