### ISSUE TITLE
Minimap nodes draw above standard tracking dots.

### ISSUE THREAD

**Issue by PEmergence** [shagu/pfQuest#34]
Repro

- Search pfQuest for Silverleaf
- Click result to add nodes to map
- Activate Find Herbs
- pfQuest map nodes obscure stock UI find herb markers

Workaround is to set minimap node transparency to ~0.5 but results are not ideal, messy to read

**Comment by Cephel** [comment]
To add to this, they also block the tooltip, when you hover over them.

**Comment by shagu** [comment]
I have no idea how I could put them in background. I now spent two hours trying to access the default tracking circles, without any success.

**Comment by Lichery** [comment]
I'm not exactly sure, but it looks like these textures
[ObjectIcons.zip](https://github.com/shagu/pfQuest/files/1679672/ObjectIcons.zip)
path Interface\\Minimap\\ObjectIcons

**Comment by Lichery** [comment]
yes, these are exactly these textures

**Comment by Muehe** [comment]
I had a look at this, too. Preliminary results:

## Standard behaviour

This is the normal situation (Frame stack by DevTools):

![minimap01](https://user-images.githubusercontent.com/8838573/35774749-93b872da-0978-11e8-9243-f8299df9eec4.png)

Only part I am sure about is that they are not part of `MinimapBackdrop`, as this can be hidden without the notes disappearing (it's the circle around the map). When `Minimap` is hidden, the tracking blips disappear as well. DevTool's `/dump Minimap:GetChildren()` shows ~16 members, and only a few of them are frames, so maybe the tracking blips get represented as member data of `Minimap` instead of their own frames. Also, note the weird table with `FrameLevel` 3, it appears to have a random ID on each restart/reload. Most likely access to the blips is deliberately restricted, for example to prevent "forwarding" of tracking information to other players (see [this random reddit post](https://www.reddit.com/r/wowaddons/comments/6t8bg1/addon_to_filter_minimap_trackingxpost_from_rwow/dlje230/)).

## pfQuest behaviour

This happens when pfQuest notes get added normally, tracking blip is barely visible and pfQuest tool tip is active:

![minimap02](https://user-images.githubusercontent.com/8838573/35774765-6b1bb1b0-0979-11e8-90c6-233f5e0dd77b.png)

## Lowering FrameLevel to 1

Setting the `FrameLevel` of pfQuest notes from 2 to 1 lets you view the tracking blip tool tips, but it means the pfQuest minimap notes will never show tooltips, even if there is no tracking blip beneath them:

![minimap03](https://user-images.githubusercontent.com/8838573/35774817-5de2943a-097b-11e8-88e8-eb12f67977ac.png)

## Lowering note size from 16x16 to 12x12

Making the pfQuest notes smaller does help with tracking blip visibility, but it doesn't solve the tool tip problem:

![minimap06](https://user-images.githubusercontent.com/8838573/35774850-33b85d60-097c-11e8-8ebb-97a60640bfd0.png)

## Possible solution

I feel the best way would be somewhat like the Gatherer behaviour, where it redraws notes to circles on the minimap, shortly before they enter the tracking distance:

![gatherer](https://addons.rising-gods.de/sites/default/files/2016-11/Gatherer_0_0%5B1%5D.jpg)

Perhaps we could do the same for pfQuest notes (if they are ores/herbs/treasures [[relevant Gatherer source](https://github.com/jsb/Gatherer/blob/master/GatherIcons.lua#L25-L96)]) and at the same time lower their `FrameLevel` to 1 or disabling their tool tip in some other fashion. There are some ores/herbs with alternative spawns, so having the tracking blip tooltips would be desirable.

Btw. the [Minimap frame](http://wowprogramming.com/docs/widgets/Minimap) has a [SetBlipTexture](http://wowprogramming.com/docs/widgets/Minimap/SetBlipTexture) function, which allows one to set custom textures file instead of the ObjectIcons one mentioned by Lichery above.

**Comment by dogmax** [comment]
I disagree with the gatherer solution. 

I think the best option (if you cant redraw the yellow dots) is to make PfQuest dots smaller or turn them into a circle, where the yellow dot can fill the circle. Both solutions enable you to see both.

**Comment by Road-block** [comment]
I have been making this change in my local copy for a while, using the node3 option (hollow texture) specifically for minimap poi.  
https://github.com/Road-block/pfQuest/commit/0240efc3013b4fe6fbd4dd563ce1000d8eaea0a9
As far as the built-in poi there is indeed no API access to their location by design, either directly or through frame enumeration.  
The only thing you can do is texture replacement.

**Comment by shagu** [comment]
The latest version on `master`-branch has an option to use cut-out icons on the minimap.
![image](https://user-images.githubusercontent.com/11586807/40061360-09cf045a-5859-11e8-9f0e-79e626ee1d1f.png)

In addition to that, you can hold down the shift-key while hovering the minimap to hide the pfQuest nodes.

Thanks for all your input.
I believe that should fix all the mentioned issues :)
