### ISSUE TITLE
Tooltip flickering (map/minimap)

### ISSUE THREAD

**Issue by nonameform** [shagu/pfQuest#74]
Whenever I hover over a quest/spawn/object on minimap/map, there is a noticeable flickering on the tooltip. I'm running en-US Vanilla version 1.12 and the problem is always there, even when I do a fresh addon install from scratch and it is the only addon enabled.

**Comment by shagu** [comment]
Thanks for your report. This happened due to a floating point issue which occured on some UIScales. It should be fixed with the latest release [4.5.8] :)

Related changes:
https://github.com/shagu/pfQuest/commit/4e2fb87bfe52240a80c5cc8b28656bee66bc5b3c
https://github.com/shagu/pfQuest/commit/517d6a56609efca34ba2deb5da4c3ec2e9135362

**Comment by nonameform** [comment]
Awesome. Thank you for that fix! I should have reported it earlier as it was bothering me for quite a while.
