### ISSUE TITLE
problems with pfQuest tracker and tracking marks in original QuestLog

### ISSUE THREAD

**Issue by Artur91425** [shagu/pfQuest#95]
The tracker breaks the original logic of the tracker in the questlog.
The following problems were found:
1) Quests that are added to the pfQuest tracker (by default, all starting quests ) are not marked as active tracking in the standard questlog frame (there is no check mark around to the quest name and a red indicator for the quest is on, signaling that the quest is not being tracked, although this not this way)
2) There is no way to turn off quest tracking through the original questlog (shift click on the quest in the questlog). The quest that I am trying to disable in this way is re-added to the pfQuest tracker
https://youtu.be/Rhx8YP-NYpg
3) If you enable quest tracking in the original questlog (make sure the check mark is checked), then the pfQuest function starts working incorrectly to disable tracking (ctrl click on the quest in the pfQuest tracker). On the world map, tracking is disabled, but the quest remains in the pfQuest tracker.
https://youtu.be/BxqLTm-s0TU
4) In my opinion, the logic of the pfQuest tracker is not quite correct. If I remove a quest from the pfQuest tracker (ctrl click), then the nodes on the minimap/world map also disappear. There are times when you need to display in one of these places. Either in the tracker or on the map and do not display or hide in both places. For example, a quest where you need to kill a bunch of mobs throughout the location. pfQuest will "litter" the world map with a lot of nodes. In this situation, I would prefer not to remove the quest in the tracking of the tracker, but I would like to hide the notes on the world map so as not to "litter" it.

**Comment by shagu** [comment]
It's not a bug to me and works as intended. It's supposed to be a map-tracker that provides overview to all visible quest on the current map, and not a quest tracker that provides a 2nd questlog with the same features. 

Originally, it was only visible while the map is shown and anchored to it, but due to requests I made it into something that is visible all the time. I saw it coming like this, that one day someone will make an issue and requests turn the map tracker into a quest tracker.

Actually, I like it as is and don't plan to rewrite the tracker. You can type `/db tracker` to disable pfQuests map tracker and get back the original one, that will only show tracked quests if you prefer it like that.

As an alternative, you can also rewrite the pfQuest tracker to make it work like the quest tracker while not breaking the functionality it has right now (good luck). But I will not make it.

Also, since the game only allows to set a fixed number of tracked quests, I didn't like the quest tracking thing at all and prefer to have the tracker always show all quests that are actually on the current map aka. the active ones.
